#
###################################
# Site wide configuration
####################################
#
title: ~/gabby
email:
description: Homepage 
url: 

#
###################################
# Jekyll configuration
####################################
#
timezone:          Central/Chicago
markdown:          kramdown
highlighter:       rouge

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Gabby Ortman
  avatar: avatar.jpg
  job: "Software Engineer @ Red Nova Labs"
  bio: "there's no place like ~/"
  email:
  disqus-shortname:
  twitter: GabbyOrtman
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: nucle0tides
  gitlab: #username
  skype: #username
  xing: #username
  instagram: gabby.ortman
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
